//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResMonTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowResIcon {
            get {
                return ((bool)(this["ShowResIcon"]));
            }
            set {
                this["ShowResIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCpuIcon {
            get {
                return ((bool)(this["ShowCpuIcon"]));
            }
            set {
                this["ShowCpuIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int PlotItems {
            get {
                return ((int)(this["PlotItems"]));
            }
            set {
                this["PlotItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int PlotWidth {
            get {
                return ((int)(this["PlotWidth"]));
            }
            set {
                this["PlotWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int PlotHeight {
            get {
                return ((int)(this["PlotHeight"]));
            }
            set {
                this["PlotHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateGray")]
        public global::System.Drawing.Color PlotGridColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotGridColor"]));
            }
            set {
                this["PlotGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SwapColor {
            get {
                return ((global::System.Drawing.Color)(this["SwapColor"]));
            }
            set {
                this["SwapColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color RamColor {
            get {
                return ((global::System.Drawing.Color)(this["RamColor"]));
            }
            set {
                this["RamColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color CpuTotalColor {
            get {
                return ((global::System.Drawing.Color)(this["CpuTotalColor"]));
            }
            set {
                this["CpuTotalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CpuMaxColor {
            get {
                return ((global::System.Drawing.Color)(this["CpuMaxColor"]));
            }
            set {
                this["CpuMaxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color Cpu1Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu1Color"]));
            }
            set {
                this["Cpu1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 246, 42")]
        public global::System.Drawing.Color Cpu2Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu2Color"]));
            }
            set {
                this["Cpu2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 186, 0")]
        public global::System.Drawing.Color Cpu3Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu3Color"]));
            }
            set {
                this["Cpu3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236, 117, 39")]
        public global::System.Drawing.Color Cpu4Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu4Color"]));
            }
            set {
                this["Cpu4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 0, 59")]
        public global::System.Drawing.Color Cpu5Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu5Color"]));
            }
            set {
                this["Cpu5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 49, 108")]
        public global::System.Drawing.Color Cpu6Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu6Color"]));
            }
            set {
                this["Cpu6Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("215, 0, 122")]
        public global::System.Drawing.Color Cpu7Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu7Color"]));
            }
            set {
                this["Cpu7Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174, 50, 136")]
        public global::System.Drawing.Color Cpu8Color {
            get {
                return ((global::System.Drawing.Color)(this["Cpu8Color"]));
            }
            set {
                this["Cpu8Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color IconBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["IconBackgroundColor"]));
            }
            set {
                this["IconBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int IconSize {
            get {
                return ((int)(this["IconSize"]));
            }
            set {
                this["IconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSlateGray")]
        public global::System.Drawing.Color PlotRectColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotRectColor"]));
            }
            set {
                this["PlotRectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color PlotMarkerColor {
            get {
                return ((global::System.Drawing.Color)(this["PlotMarkerColor"]));
            }
            set {
                this["PlotMarkerColor"] = value;
            }
        }
    }
}
